spring.application.name=helper


spring.datasource.url=${MY_USER1}
spring.datasource.username=postgres
spring.datasource.password=${MY_PASS1}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect